const API = 'https://guardian-ai-backend-7gm6.onrender.com/';
const state = { conversation: [], timeline: [], analysis: { risk_score: 0, risk_level: 'low', language: '—', indicators: [], explanation: 'Messages will be assessed as the conversation develops.', recommended_action: 'Continue monitoring' }, cases: [] };
const signals = [
  ['Age targeting', /\bhow old\b|\bage\b|kitne saal|उम्र/i, 14, 'The message probes the user’s age.'],
  ['Age-related flattery', /mature for your age|so mature|समझदार/i, 8, 'The speaker uses age-related flattery.'],
  ['Boundary testing', /parents?.*(check|phone)|who.*home|alone\b|घर.*कौन/i, 8, 'The speaker is testing trusted-adult supervision.'],
  ['Secrecy request', /don'?t tell|keep.*secret|mat batana|मत बताना|सांगू नको/i, 25, 'The speaker is encouraging secrecy from trusted adults.'],
  ['Platform migration', /move.*(private|somewhere|app)|telegram|snap(chat)?|private.*chat|खाजगी/i, 17, 'The speaker is attempting to move the conversation to a more private channel.'],
  ['Image request', /send.*(picture|photo|pic)|send me.*image|फोटो.*पाठव/i, 27, 'The speaker is requesting an image.'],
  ['Targeted insult', /\b(ugly|loser|stupid|worthless)\b|बेकार/i, 16, 'The message contains a targeted insult.'],
  ['Threat', /\b(hurt|kill|expose) you\b|i.?ll.*ruin|मार/i, 28, 'The message contains threatening language.']
];
function localAnalyze(message, history) { const text=message.toLowerCase(), old=history.join(' ').toLowerCase(); const found=[], reasons=[]; let event=0; signals.forEach(([n,p,w,r])=>{if(p.test(text)){found.push(n);event+=w;reasons.push(r)}}); const past=new Set(signals.filter(([n,p])=>p.test(old)).map(x=>x[0])); const all=new Set([...past,...found]); let bonus=0;if(found.length&&all.size>=3&&['Age targeting','Boundary testing','Secrecy request'].some(x=>all.has(x)))bonus+=8;if(found.includes('Platform migration')&&all.has('Age targeting')&&all.has('Secrecy request'))bonus+=7;if(found.includes('Image request')&&all.has('Secrecy request')&&all.has('Platform migration'))bonus+=8;let prior=0;signals.forEach(([,p,w])=>{if(p.test(old))prior+=w});let score=found.length?Math.min(100,event+bonus+Math.min(45,Math.round(prior*.55))):Math.round(prior*.45);let language=/[\u0900-\u097F]/.test(message)?(/कुणाला|आपण|बोलतोय|सांगू/.test(message)?'Marathi / Devanagari':'Hindi / Devanagari'):/\b(mat batana|baat karte|tum|hai)\b/i.test(message)?'Hinglish':'English'; const level=score>=75?'high':score>=40?'medium':'low'; if(bonus)reasons.push('Multiple contextual indicators are occurring together, increasing concern.');return {risk_score:score,risk_level:level,language,indicators:found,explanation:reasons.join(' ')||'No strong behavioral risk signal was detected in this new message.',recommended_action:score>=75?'Escalate for human review':score>=40?'Warn and recommend review':'Continue monitoring'}; }
async function analyze(message){try{const r=await fetch(API+'/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,conversation:state.conversation.map(x=>x.text)})});if(!r.ok)throw Error();document.querySelector('#mode').textContent='API protection engine';return await r.json()}catch{document.querySelector('#mode').textContent='Local protection engine';return localAnalyze(message,state.conversation.map(x=>x.text));}}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addMessage(text, sender='Unknown User'){state.conversation.push({sender,text});const box=document.querySelector('#messages'),el=document.createElement('div');el.className='message '+(sender==='Child'?'child':'incoming');el.innerHTML=`<b>${esc(sender)}</b><p>${esc(text)}</p>`;box.append(el);box.scrollTop=box.scrollHeight}
function renderAnalysis(a){state.analysis=a;document.querySelector('#score').textContent=a.risk_score;const level=document.querySelector('#level');level.textContent=a.risk_level.toUpperCase();level.className=a.risk_level;const fill=document.querySelector('#meterFill');fill.style.width=a.risk_score+'%';fill.style.background=a.risk_level==='high'?'var(--red)':a.risk_level==='medium'?'var(--yellow)':'var(--green)';document.querySelector('#language').textContent='Language: '+a.language;document.querySelector('#explanation').textContent=a.explanation;document.querySelector('#action').textContent=a.recommended_action;const ind=document.querySelector('#indicators');ind.className=a.indicators.length?'':'empty';ind.innerHTML=a.indicators.length?a.indicators.map(x=>`<li>✓ ${esc(x)}</li>`).join(''):'<li>No concerning pattern yet</li>';if(a.indicators.length){state.timeline.push({time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),detection:a.indicators.join(' · '),risk_score:a.risk_score,risk_level:a.risk_level});document.querySelector('#timeline').innerHTML=state.timeline.map(x=>`<div class="timeline-item">${x.time}<b>${esc(x.detection)}</b> · ${x.risk_score}/100</div>`).join('')}document.querySelector('#createAlert').disabled=a.risk_score<40;document.querySelector('#safetyWarning').classList.toggle('hidden',a.risk_score<40)}
async function incoming(text){addMessage(text);renderAnalysis(await analyze(text))}
document.querySelector('#messageForm').addEventListener('submit',async e=>{e.preventDefault();const input=document.querySelector('#messageInput'),sender=document.querySelector('#senderSelect').value;if(!input.value.trim())return;const text=input.value.trim();if(sender==='Child')addMessage(text,'Child');else await incoming(text);input.value=''})
const demo=[['Hey! How are you?','Unknown User'],["I'm good 😊",'Child'],['How old are you?','Unknown User'],["I'm 15.",'Child'],["You're really mature for your age.",'Unknown User'],['Do your parents check your phone?','Unknown User'],["Don't tell anyone we're talking, okay?",'Unknown User'],["Let's move this conversation somewhere private.",'Unknown User'],['Can you send me a picture?','Unknown User']];
document.querySelector('#demo').onclick=async()=>{if(document.querySelector('#demo').disabled)return;document.querySelector('#demo').disabled=true;document.querySelector('#messages').innerHTML='';state.conversation=[];state.timeline=[];renderAnalysis({risk_score:0,risk_level:'low',language:'—',indicators:[],explanation:'Demo is beginning with a normal conversation.',recommended_action:'Continue monitoring'});for(const [text,sender] of demo){await new Promise(r=>setTimeout(r,700));if(sender==='Child')addMessage(text,sender);else await incoming(text)}document.querySelector('#demo').disabled=false;toast('Demo complete — alert is ready for review.');}
document.querySelectorAll('.nav').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#'+btn.dataset.page).classList.add('active');if(btn.dataset.page==='dashboard')loadCases()});
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function createAlert(){const data={...state.analysis,conversation:state.conversation,timeline:state.timeline,status:state.analysis.risk_score>=75?'Escalated':'Reviewing'};try{const r=await fetch(API+'/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error();const c=await r.json();state.cases.unshift(c);toast(`${c.case_code} created for human review.`)}catch{const c={...data,case_code:'GA-'+(1047+state.cases.length),created_at:new Date().toISOString()};state.cases.unshift(c);toast(`${c.case_code} saved locally for this session.`)}}
document.querySelector('#createAlert').onclick=createAlert;document.querySelector('#block').onclick=()=>toast('Block request noted — no automatic action was taken.');
async function loadCases(){try{const r=await fetch(API+'/cases');if(r.ok)state.cases=await r.json()}catch{}const cases=state.cases;document.querySelector('#caseCount').textContent=42+cases.length;document.querySelector('#activeCount').textContent=12+cases.filter(x=>['Reviewing','Escalated'].includes(x.status)).length;document.querySelector('#highCount').textContent=8+cases.filter(x=>x.risk_level==='high').length;const sample=[{case_code:'GA-1047',risk_score:88,risk_level:'high',indicators:['Grooming indicators'],language:'Hinglish',status:'Escalated'},{case_code:'GA-1046',risk_score:71,risk_level:'medium',indicators:['Cyberbullying'],language:'Marathi',status:'Reviewing'},{case_code:'GA-1045',risk_score:18,risk_level:'low',indicators:['None'],language:'English',status:'Resolved'}];document.querySelector('#casesTable').innerHTML=[...cases,...sample].map(c=>`<tr data-case="${esc(c.case_code)}"><td>${esc(c.case_code)}</td><td class="risk ${c.risk_level}">${c.risk_score}/100</td><td>${esc(c.indicators.join(', '))}</td><td>${esc(c.language)}</td><td>${esc(c.status)}</td></tr>`).join('');document.querySelectorAll('#casesTable tr').forEach(row=>row.onclick=()=>showCase(row.dataset.case));}
function showCase(code){const c=state.cases.find(x=>x.case_code===code);document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));document.querySelector('[data-page="cases"]').classList.add('active');document.querySelector('#cases').classList.add('active');if(!c){document.querySelector('#caseDetail').textContent='Demo case: detailed data is available for newly created alerts.';return}document.querySelector('#caseDetail').className='panel case-detail';document.querySelector('#caseDetail').innerHTML=`<h2>CASE #${esc(c.case_code)}</h2><p><strong class="${c.risk_level}">${c.risk_level.toUpperCase()} RISK · ${c.risk_score}/100</strong> &nbsp; ${esc(c.status)}</p><h3>Detected indicators</h3><p>${c.indicators.map(esc).join(' · ')}</p><h3>AI explanation</h3><p>${esc(c.explanation)}</p><h3>Conversation</h3><p>${c.conversation.map(m=>`<b>${esc(m.sender)}:</b> ${esc(m.text)}`).join('<br>')}</p><h3>Risk timeline</h3><p>${c.timeline.map(t=>`${esc(t.time)} — ${esc(t.detection)} (${t.risk_score}/100)`).join('<br>')}</p><div class="case-actions"><button class="primary" onclick="updateStatus('${esc(c.case_code)}','Escalated')">Escalate</button><button class="secondary" onclick="updateStatus('${esc(c.case_code)}','Reviewing')">Mark Reviewing</button><button class="secondary" onclick="updateStatus('${esc(c.case_code)}','Resolved')">Resolve</button><button class="secondary" onclick="updateStatus('${esc(c.case_code)}','Dismissed')">Dismiss</button></div>`}
window.updateStatus=async(code,status)=>{const c=state.cases.find(x=>x.case_code===code);if(!c)return;c.status=status;try{await fetch(API+'/cases/'+code,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})})}catch{}showCase(code);toast(`Case marked ${status}.`)};
loadCases();
